### ISSUE TITLE
System service for ssh-cron

### ISSUE THREAD

**Issue by mhalano** [fbb-git/ssh-cron#1]
I think should have some kind of service (possible Systemd service or sysvinit compatible service) to start ssh-cron with the system and acts like a replacement for anacron/cron.

**Comment by fbb-git** [comment]
Dear Marcos H. Alano, you wrote:
> I think should have some kind of service (possible Systemd service or
sysvinit compatible service) to start ssh-cron with the system and acts like a
replacement for anacron/cron.

Thanks for your suggestion about ssh-cron. However, I don't think that what
you propose is what you want. The idea of ssh-cron is that you allow yourself
access to remote computers using an ssh certificate. Once this is realized
ssh-cron uses the facilities of ssh-agent to allow it also to access those
remote computers. The man-page describes this in more or less
detail. Moreover, ssh-cron asks you for a passphrase with which your ssh-cron
commands are protected. That passphrase must be provided by you, and cannot be
provided by systemd/sysvinit-like facilities.

Cheers,

-- 
    Frank B. Brokken
    Center for Information Technology, University of Groningen
    (+31) 50 363 9281 
    Public PGP key: http://pgp.surfnet.nl
    Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
